### PR TITLE
Fix error passing bug

### LINKED ISSUE #223: When using JSON mode, errors sent to stderr are not correctly passed to callback function
**Describe the bug**
When python shell is used in "json" mode errors are not caught and returned via the callback function, as pythonshell tries to pass the error as JSON.

**Python code**
```python
import sys
import json

print(something) # erroneous line that causes a "NameError: name 'something' is not defined"

inputData = json.loads(sys.argv[1])
inputData["data"] += "pythonstuff"

print(json.dumps(inputData))

```
**Javascript code**
```javascript
const {PythonShell} = require("python-shell");
const scriptName = "./lib/hello.py";
const args = {data: "test"};

const options = {
  mode: "text",
  pythonPath: "python3",
  scriptPath: process.cwd(),
  args: JSON.stringify(args),
};
PythonShell.run(scriptName, options, (err, results) => {
  if (err) {
    console.log("error: ", err);
  } else {
    console.log("results: ", results);
  }
});
```

**Expected behavior**
I expect the callback function to catch and log the python error, as it does correctly do in text mode, then finish running the javascript code without crashing node.

**Actual behavior**
The javascript code crashes with error `SyntaxError: Unexpected token T in JSON at position 0` because the Traceback sent to stderr is attempting to be parsed as JSON.

**Other Information (please complete the following information):**
 - OS: elementary OS 5.1.5 Hera
 - Python Version: Python 3.7.4
 - Node Version: v13.9.0.

### PR DESCRIPTION
**Pull request by AshleySetter**
Fixes #223

### CODE REVIEW

File: index.ts [hunk 1]
```diff
@@ -135,7 +135,7 @@ export class PythonShell extends EventEmitter{
         this.mode = options.mode || 'text';
         this.formatter = resolve('format', options.formatter || this.mode);
         this.parser = resolve('parse', options.parser || this.mode);
-        this.stderrParser = resolve('parse', options.stderrParser || this.mode);
+        this.stderrParser = resolve('parse', options.stderrParser || 'text');
```
Comment (Almenon) [inline index.ts:138]:
```suggestion
        // We don't expect users to ever format stderr as JSON so we default to text mode
        this.stderrParser = resolve('parse', options.stderrParser || 'text');
```

Comment (Almenon) [reply index.ts:138]: More comments the better IMO. The PR also needs a documentation update but I can do that myself after I merge in the PR :)

**Comment by Almenon** [comment]
Thanks for the PR!
